### ISSUE TITLE
ideas for more presenters

### ISSUE THREAD

**Issue by cole-brokamp** [cchmc-rug/meetings#1]
- Erika: "Intro to Shiny" (or @wolfeclw do you want to do this and have her do tidyverse instead?)
- Nobel: ?
- Josh L ?
- Philip H ?
- Nick P ?
- Lei L ?
- Nick O ?

- Cole: docker and R
- Rhonda/Weiji/Emrah: longitudinal analysis in R?

**Comment by wolfeclw** [comment]
I would be happy to do either.  I already made the tidyverse presentatin, so it could be easier for me to do that.  One thing I might want to look at though is to see if we can get an idea of who will attend. 
 Depending on the audience, an intro to tidyverse could be overkill.

**Comment by cole-brokamp** [comment]
a talk on using the CCHMC HPC with R (including Singularity)

**Comment by cole-brokamp** [comment]
ran into Nick O, he volunteered to do a talk
